### ISSUE TITLE
"Unreleased" link broken

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/auto-changelog#39] opened 2021-05-02 05:32 UTC
The `Unreleased` URL is at least sometimes generated in a broken state, e.g.:

```
[unreleased]: https://github.com/MetaMask/post-message-stream.git/v3.0.0...HEAD
```

The above 404s. The correct URL would be:
```
[unreleased]: https://github.com/MetaMask/post-message-stream/compare/v3.0.0...HEAD
```

It's also unclear to me whether it should force-lowercase `unreleased`? It overwrote a link with `Unreleased` in my testing.

**Comment by Gudahtt** [comment] 2021-05-04 02:53
I can't reproduce this. It seems to always be upper-case in my testing, and I haven't seen that mangled URL used yet.

**Comment by Gudahtt** [comment] 2021-05-04 18:08
After speaking with @rekmarks about this, our best guess is that this error was encountered with an older version of this repo. Closing for now since we can't repro this.

**Closed** 2021-05-04 21:11 UTC
Labels: bug
